app/views/mod_views.py
from flask import Blueprint, render_template, request, redirect, url_for, flash
from flask_security import login_required, current_user
from bson.json_util import dumps
from db import *
mod_blueprint = Blueprint('mods', __name__, template_folder='templates')

@mod_blueprint.route("/")
@login_required
def index():
    mod_messages=get_group_messages()
    for i in mod_messages:
        i['count']=group_transactions.count_documents({'body':i['_id']})
        if chat_db.flagged_messages.find_one({'_id':i['_id']}):
            i['flagged']=True
        else:
            i['flagged']=False
    mod_messages=sorted(mod_messages, key=lambda i:i['count'], reverse=True)
    return render_template('mod/index.html', mod_messages=mod_messages)

@mod_blueprint.route("/user")
@login_required
def users():
    return render_template('mod/users.html')

@mod_blueprint.route("/profile")
@login_required
def profile():
    return render_template('mod/profile.html')

@mod_blueprint.route("/flag/<messageId>")
@login_required
def flag(messageId):
    chat_db.flagged_messages.insert_one(transaction_message.find_one({"_id":messageId}))
    flash("Flagged the message", "success")
    return redirect(url_for("mods.index"))

@mod_blueprint.route("/create", methods=['GET', 'POST'])
@login_required
def create_channel():
    if request.method == 'POST':
        room_name = request.form.get('room_name')
        usernames = [i['username'] for i in list(users_collection.find({"roles":[]},{'username':1, '_id':0}))] 
        type_room="Channel"
        if len(room_name) and len(usernames):
            room_id = save_room(room_name, current_user.username, type_room, official=True)
            add_room_members(room_id, room_name, usernames, current_user.username, type_room)
            flash("channel created Successfully", "success")
            return redirect(url_for("mods.index"))
            #return redirect(url_for('mod.view_room', room_id=room_id))
        else:
            flash("Failed to create room", 'error')

@mod_blueprint.route('/createRoom', methods=['POST'])
@login_required
def createRoom():
    if request.method == 'POST':
        room_name = request.form.get('room_name')
        banned=['<img src="/static/icons/patch-check-fill.svg">']
        for i in banned:
            if i in room_name:
                flash('You cannot Add that to symbol in the room title')
                return redirect(url_for('public.home_page'))
        usernames = request.form.getlist('friends')
        type_room=request.form.get('type')
        if len(room_name) and len(usernames):
            room_id = save_room(room_name, current_user.username, type_room)
            if current_user.username in usernames:
                usernames.remove(current_user.username)
            add_room_members(room_id, room_name, usernames, current_user.username, type_room)
            return redirect(url_for('public.view_room', room_id=room_id))
        else:
            flash("Failed to create room", 'error')

app/templates/mod/index.html
<!DOCTYPE html>
<html>

<head>
    <title>mod: {{ current_user.username }}</title>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="{{ url_for('static', filename='bootstrap/css/bootstrap.min.css') }}" rel="stylesheet">
    <script src="{{ url_for('static', filename='bootstrap/js/bootstrap.bundle.min.js') }}"></script>
    
</head>

<body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark" role="navigation">
        <div class="container-fluid">
            
            <div class="collapse navbar-collapse" id="admin-navbar-collapse">
                <a class="navbar-brand" href="/mod">Mod</a>
                <ul class="navbar-nav mr-auto">
                    <li>
                        <a class="nav-link" href="/mod">
                            Home</a>
                    </li>
                </li>
                <li class="nav-item dropdown">
                  <a class="nav-link" data-bs-toggle="dropdown" aria-expanded="false" href="#"><img
                      src="/static/icons/people-fill.svg"></a>
                  <div class="dropdown-menu">
                    <form class="form" action="{{url_for('mods.create_channel')}}" method="POST" style="padding: 10px;">
                      <input type="hidden" name="csrf_token" value="{{ csrf_token() }}" />
                      <div class="mb-3">
                        <label for="roomname" class="form-label">Room Name</label>
                        <input type="text" name="room_name" autocomplete="off" id="roomname">
                      </div>
                      <label for="type">Type of room</label>
                      <select class="form-select" id="type" name="type">
                        <option value="Channel">Channel</option>
                      </select>
          
                      <button type="submit">Submit</button>
                    </form>
                  </div>
                </li>
                    <li class="active">
                        <a class="nav-link" href="/mod/user">
                            User</a>
                    </li>
                    <li>
                </ul>
                <ul class="nav navbar-nav navbar-right">
                    <li>
                        <a class="nav-link" href="/mod/profile">Profile</a>
                    </li>
                    <li>
                        <a class="nav-link" href="/logout">Logout</a>
                    </li>
                </ul>
            </div>
        </div>
    </nav>
    
    <div class="container">
        
        {% block body %}
        <div class="row row-cols-1 row-cols-md-3 g-4">

       
            {% for message in mod_messages %}
            <div class="col">
                <div class="card">
                    <div class="card-body">
                        <h5 class="card-title">Message: {{message.text}}</h5>
                        <h5>Message Count: {{message.count}}</h5>
                        <h5>Message Flagged: {{message.flagged}}</h5>
                        {%if not message.flagged %}
                            <a class="btn btn-primary" href="{{url_for('mods.flag', messageId=message._id)}}" role="button">Flag</a>
                        {%else%}
                        <h5>Already Flagged</h5>
                        {%endif%}
                    </div>
                </div>
            </div>
            {% endfor %} 
        </div>
        {% endblock %}
    </div>
    {% include "security/_messages.html" %}
</body>

app/templates/mod/profile.html
{% extends "mod/index.html" %}
{% block body %}
<table class="table table-light mb-2">
    <tbody>
      <tr>
        <th scope="row"></th>
        <td>Username</td>
        <td>{{current_user.username}}</td>
      </tr>
      <tr>
        <th scope="row"></th>
        <td>Email</td>
        <td>{{current_user.email}}</td>
      </tr>
      <tr>
        <th scope="row"></th>
        <td>Role</td>
        <td>Moderator</td>
      </tr>
    </tbody>
  </table>
{% endblock %}

app/templates/mod/users.html
{% extends "mod/index.html" %}
{% block body %}
<h1>This is Users</h1>
{% endblock %}