app/views/public_views.py
from datetime import datetime
from flask import Blueprint, render_template, flash, send_file
from flask import redirect, request, render_template, url_for
from flask_security import login_required, current_user
from bson.json_util import dumps
import secrets
from bson import ObjectId
from flask_socketio import SocketIO
from db import *
public_blueprint = Blueprint('public', __name__, template_folder='templates', url_prefix="/user")
socketio = SocketIO()

requestUser=chat_db.get_collection("requests")
friends=chat_db.get_collection("friends")

@public_blueprint.route('/')
@login_required
def home_page():
    rooms = get_rooms_for_user(current_user.username)
    friend=friends.find_one({'_id':current_user.username})
    room_title=sidebarGen()

    return render_template('public/home_page.html',rooms=rooms, friend=friend, room_title=room_title)

def sidebarGen():
    rooms = get_rooms_for_user(current_user.username)
    room_title={}
    for i in rooms:
        room_id=i["_id"]["room_id"]
        if i['type']!='chat':
            room = get_room(room_id)
            messages = get_messages(room_id, i['type'])
            room_title[room_id]=[i["room_name"], dumps(messages)]
        else:
            room = get_room(room_id)
            if room and is_room_member(room_id, current_user.username):
                room_members = get_room_members(room_id)
                messages = get_messages(room_id, i['type'])
                roomMembers=[i["_id"]["username"] for i in room_members if i["_id"]["username"]!=current_user.username]
            room_title[room_id]=[roomMembers[0], dumps(messages)]
    return room_title

@public_blueprint.before_request

@public_blueprint.route('/search', methods=['POST'])
@login_required
def search_user():
    if request.method=='POST':
        user=request.form.get('username')
        users=list(users_collection.find({'username':user}))
        return render_template('public/search.html', users=users)

@public_blueprint.route('/request/<username>', methods=['GET','POST'])
@login_required
def request_user(username):
    requestUser.insert_one(
        {'from': current_user.username, 'from_name':current_user.name,'to':username, 'created_at': datetime.now()})
    flash("Request Sent", 'success')
    return redirect("/")

@public_blueprint.route('/requests', methods=['GET','POST'])
@login_required
def requests(**kwargs):
    
    Request=[requestUser.find_one({'to':current_user.username})]
    return render_template('public/request.html', users=Request)

@public_blueprint.route('/accept/<username>', methods=['GET', 'POST'])
@login_required
def accept(username):
    room_name="#"
    requestUser.find_one_and_delete({'from': username,'to':current_user.username})
    room_id = save_room(room_name, current_user.username, 'chat')
    add_room_member(room_id, room_name, username, current_user.username,True, 'chat')
    addFriend(username, current_user.username)
    return redirect("/")

def addFriend(user1, user2):
    if friends.find_one({'_id':user1}):
        friends.update_one({'_id':user1}, {'$push':{'friends':user2}})
    else:
        friends.insert_one({'_id':user1, 'friends':[user2]})
    if friends.find_one({'_id':user2}):
        friends.update_one({'_id':user2}, {'$push':{'friends':user1}})
    else:
        friends.insert_one({'_id':user2, 'friends':[user1]})


@public_blueprint.route('/leave/<room_id>', methods=['GET','POST'])
@login_required
def leave_room(room_id):
    if room_members_collection.find_one({'_id.room_id': ObjectId(room_id), '_id.username':current_user.username})['is_room_admin']:
        room_members_collection.delete_one({'_id.room_id': ObjectId(room_id), '_id.username':current_user.username})
        rooms_collection.delete_one({'_id':ObjectId(room_id)})
    return redirect("/")


@public_blueprint.route('/create-room', methods=['POST'])
@login_required
def create_room():
    if request.method == 'POST':
        room_name = request.form.get('room_name')
        banned=['<img src="/static/icons/patch-check-fill.svg">']
        for i in banned:
            if i in room_name:
                flash('You cannot Add that to symbol in the room title')
                return redirect(url_for('public.home_page'))
        usernames = request.form.getlist('friends')
        type_room=request.form.get('type')
        if len(room_name) and len(usernames):
            room_id = save_room(room_name, current_user.username, type_room)
            if current_user.username in usernames:
                usernames.remove(current_user.username)
            add_room_members(room_id, room_name, usernames, current_user.username, type_room)
            return redirect(url_for('public.view_room', room_id=room_id))
        else:
            flash("Failed to create room", 'error')
    #return render_template('chat/create_room.html', message=message)

@public_blueprint.route('/createRoom', methods=['POST','GET'])
@login_required
def createRoom():
    return request.form
@public_blueprint.route('/rooms/<room_id>/edit', methods=['GET', 'POST'])
@login_required
def edit_room(room_id):
    room = get_room(room_id)
    if room and is_room_admin(room_id, current_user.username):
        existing_room_members = [member['_id']['username'] for member in get_room_members(room_id)]
        room_members_str = ",".join(existing_room_members)
        message = ''
        if request.method == 'POST':
            room_name = request.form.get('room_name')
            room['name'] = room_name
            update_room(room_id, room_name)

            new_members = [username.strip() for username in request.form.get('members').split(',')]
            members_to_add = list(set(new_members) - set(existing_room_members))
            members_to_remove = list(set(existing_room_members) - set(new_members))
            if len(members_to_add):
                add_room_members(room_id, room_name, members_to_add, current_user.username)
            if len(members_to_remove):
                remove_room_members(room_id, members_to_remove)
            message = 'Room edited successfully'
            room_members_str = ",".join(new_members)
            room_title=sidebarGen()
        return render_template('chat/edit_room.html', room=room, room_members_str=room_members_str, message=message, room_title=room_title)
    else:
        return "Room not found", 404

@public_blueprint.route('/rooms/<room_id>/')
@login_required
def view_room(room_id):
    room = get_room(room_id)
    friend=friends.find_one({'_id':current_user.username})
    rooms = get_rooms_for_user(current_user.username)
    if room and is_room_member(room_id, current_user.username):
        room_members = get_room_members(room_id)
        type=room['type']
        messages = get_messages(room_id, type)
        room_title=sidebarGen()
        roomMembers=[i["_id"]["username"] for i in room_members if i["_id"]["username"]!=current_user.username]
        return render_template('public/view_room.html',rooms=rooms, username=current_user.username, room=room, room_members=room_members,
                               messages=messages, roomMembers=roomMembers, friend=friend, room_title=room_title)
    else:
        return "Room not found", 404


@public_blueprint.route('/rooms/<room_id>/messages/')
@login_required
def get_older_messages(room_id):
    room = get_room(room_id)
    if room and is_room_member(room_id, current_user.username):
        messages = get_messages(room_id)
        return dumps(messages)
    else:
        return "Room not found", 404

@public_blueprint.route('/userSummery')
@login_required
def userSummery():
    createFolder("summery")
    messages=[]
    rooms = get_rooms_for_user(current_user.username)
    for i in rooms:
        room_id=i['_id']['room_id']
        messages.append(list(messages_collection.find({'room_id': room_id}).sort('_id', DESCENDING))[::-1])
    return str(messages)
    #with open("summery/userSummery.txt","a+") as file:
    #    file.write(messages)
    #return send_file(os.path.realpath("D:\\Projects\\messenger\\summery\\userSummery.txt"), as_attachment=True)

@public_blueprint.route('/roomSummery/<room_id>')
@login_required
def roomSummery(room_id):
    room = get_room(room_id)
    if room and is_room_member(room_id, current_user.username):
        summery(room_id, "summery/roomSummery.txt")
        return send_file(os.path.realpath("D:\\Projects\\messenger\\summery\\roomSummery.txt"), as_attachment=True)

def createFolder(directory):
    try:
        if not os.path.exists(directory):
            os.makedirs(directory)
    except OSError:
        print ('Error: Creating directory. ' +  directory)

def summery(room_id, filename):
    room = get_room(room_id)
    if room and is_room_member(room_id, current_user.username):
        createFolder("summery")
        messages = get_messages(room_id)
        messages.append({
            'username':current_user.username,
            'generated_at':datetime.now()
        })
        with open(filename,"a+") as file:
            file.write(dumps(messages))

@public_blueprint.before_request
def keyGen():
    users=list(chat_db.user.find({}, {"username":1, "_id":True}))
    for i in users:
        if chat_db.keys.find_one({"username":i['username']}):
            continue
        else:
            chat_db.keys.insert_one({"_id":i["_id"], "username":i['username'], "key":secrets.token_hex(16)})

app/views/success.py
from flask import Blueprint, render_template, request, redirect, url_for
from flask.helpers import flash
from flask_security import login_required, current_user
from app import babel
from flask import current_app as app
import gettext

members_blueprint = Blueprint('members', __name__, template_folder='templates')

'''
@babel.localeselector
def get_locale():
    translations = [str(translation) for translation in
                    babel.list_translations()]
    return request.accept_languages.best_match(translations)


def set_lang(lang):
    i18n_dir = app.config['BABEL_TRANSLATION_DIRECTORIES']
    gettext.install('lang', i18n_dir)
    trans_file = i18n_dir + lang + '/LC_MESSAGES/flask_security'
    tr = gettext.translation(trans_file, 'locale',  languages=[lang])
    tr.install(True)
    app.jinja_env.install_gettext_translations(tr)
'''

@members_blueprint.before_app_first_request
def init_my_blueprint():
    if not app.user_datastore.get_user('user@example.com'):
        app.user_datastore.create_user(email='user@example.com',
                                       password='Password1', roles=[], username='test_user')
    if not app.user_datastore.get_user('admin@example.com'):
        app.user_datastore.create_role(name="admin")
        app.user_datastore.create_user(email='admin@example.com',
                                       password='Password1', roles=['admin'], username='admin15')
    if not app.user_datastore.get_user('mod@example.com'):
        app.user_datastore.create_user(email='mod@example.com',
                                       password='Password1', roles=['moderator'], username='mod')


@members_blueprint.before_app_request
def before_request():
    '''
    lang = get_locale()
    lang = lang if lang else app.config['BABEL_DEFAULT_LOCALE']
    set_lang(lang)
    '''
    if request.path.startswith('/admin') or request.path.startswith('/mod') or request.path.startswith('/biz') or request.path.startswith('/user'):
        if not current_user.is_authenticated:
            flash("You are not authorized", "error")
            return redirect(url_for('security.login'))

@members_blueprint.route('/success')
@login_required
def member_page():
    if current_user.is_authenticated:
        """if current_user.has_role("admin"):
            return redirect('/admin')
        elif current_user.has_role("moderator"):
            return redirect('/mod')
        elif current_user.has_role("biz"):
            return redirect('/biz')
        else:
            return redirect('/user')"""
        return redirect('/user')
    else:
        return redirect(url_for('security.login'))

app/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    {% block style %}{% endblock %}
    {% block substyle %}{% endblock %}
    {% block head %}{% endblock %}

</head>
<body>
    {% include "security/_messages.html" %}
    {% block body %}{% endblock %}
</body>
</html>

app/templates/layout.html
{% extends "base.html" %}
{% block style %}
    <link href="/static/bootstrap/css/bootstrap.min.css" rel="stylesheet">
    <link href="/static/icons/bootstrap-icons.css" rel="stylesheet">
    <script src="/static/bootstrap/js/bootstrap.bundle.min.js"></script>
    <link href="/static/css/chat_style.css" rel="stylesheet">
{% endblock %}
{% block head %}
<title>Test</title>
{% endblock %}

{% block body %}
<div id="navbar" style="position: sticky; width:100%;">
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container">
    <div class="navbar-header">
      <a class="navbar-brand" href="{{ url_for('public.home_page') }}"><span class="glyphicon glyphicon-leaf text-success" aria-hidden="true"></span> {{ config.get('APP_NAME')  }}</a>
    </div>
    <form method="POST" action="{{url_for('public.search_user')}}">
      <div class="input-group">
        <form>
          <input type="hidden" name="csrf_token" value="{{ csrf_token() }}"/>
          <input type="text" class="form-control me-2" placeholder="Username" name="username" autocomplete="off">
          <button class="btn btn-success" type="submit"><img src="/static/icons/person-plus.svg" width="24" height="24"></button>
        </form>
        
      </div>
    </form>
    <div class="collapse navbar-collapse">
      <!-- <ul class="nav navbar-nav">
        <li class="nav-item"><a href="{{ url_for('public.home_page') }}" class="nav-link active">{{ _('Home Page') }}</a></li>
      </ul> -->
      <ul class="nav navbar-nav" style="margin-left: auto!important;">
        {% if current_user.is_authenticated %}
        <div class="btn-group dropstart">
          <button type="button" class="btn btn-secondary" data-bs-toggle="dropdown" aria-expanded="false">
            Create Group
          </button>
          <div class="dropdown-menu">
            <form class="px-4 py-3" action="{{url_for('public.create_room')}}" method="POST">
              <input type="hidden" name="csrf_token" value="{{ csrf_token() }}"/>
              <label>Room Name:</label>
              <input type="text" name="room_name" autocomplete="off">
              <br>
              <label>Members:</label>
              <input type="text" name="members" autocomplete="off">
              <br>
              <label for="type">Type of room</label>
              <select id="type" name="type">
                <option value="group">Group</option>
                <option value="Channel">Channel</option>
              </select>
              <br>
              
              <button type="submit">Submit</button>
            </form>
          </div>
        </div>
        <li class="nav-item">
          <a class="nav-link" href="{{url_for('public.requests')}}">Requests</a>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDarkDropdownMenuLink" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Groups
          </a>
          <ul class="dropdown-menu dropdown-menu-dark" aria-labelledby="navbarDarkDropdownMenuLink">
            <li><a class="dropdown-item" href="#">Create</a></li>
            <li><a class="dropdown-item" href="#">Another action</a></li>
            <li><a class="dropdown-item" href="#">Something else here</a></li>
          </ul>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link btn btn-secondary" href="#" id="navbarDarkDropdownMenuLink" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            <img src="/static/icons/person.svg"  width="24" height="24">
          </a>
          <ul class="dropdown-menu dropdown-menu-light" aria-labelledby="navbarDarkDropdownMenuLink">
            <li><a href="{{ url_for('members.member_page') }}" class="dropdown-item"><span class="glyphicon glyphicon-user"></span> {{ _('Profile') }}</a></li>
            <li><a href="{{ url_for('security.logout') }}" class="dropdown-item "><span class="glyphicon glyphicon-user"></span> {{ _('Logout') }}</a></li>

          </ul>
        </li>

        {% else %}
        <li class="nav-item dropdown">
          <a class="nav-link " href="#" id="navbarDarkDropdownMenuLink" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            <img src="/static/icons/person-circle.svg" width="24" height="24">
          </a>
          <ul class="dropdown-menu dropdown-menu-light" aria-labelledby="navbarDarkDropdownMenuLink">
            <li><a href="{{ url_for('security.register') }}" class="dropdown-item active"><span class="glyphicon glyphicon-user"></span> {{ _('Register') }}</a></li>
            <li><a href="{{ url_for('security.login') }}" class="dropdown-item active"><span class="glyphicon glyphicon-user"></span> {{ _('Login') }}</a></li>

          </ul>
        
        {% endif %}
      </ul>
    </div><!--/.nav-collapse -->
  </div>
</nav>
</div>
<div id="main">
  {% block content %}{% endblock %}
</div>
  

{% endblock %}